name: dbt_scooters
version: '1.0.0'
profile: dbt_scooters
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
clean-targets:
  - "target"
  - "dbt_packages"
vars:
  "dbt_date:time_zone": "Europe/Moscow"
on-run-end:
    - "grant usage on schema dbt_finance to finance;"
models:
  dbt_scooters:
    +materialized: "table"
    +on_schema_change: "append_new_columns"
    
    finance:
      +schema: "finance"
      +grants:
        select: [ "finance" ]
        
    +persist_docs:
      relation: true
      columns: true
seeds:
  dbt_scooters:
    +persist_docs:
      relation: true
      columns: true